Attraction show page
br-ndt/trip pull request #3
Opened 2022-05-03 19:59 UTC by camziny

add review tile.
add createReviews migration.
create Review model.
create attractionsReviews router.
create review seeder.

2022-05-03 20:24 UTC, dovakeen118 requested changes, later dismissed
Nice work! Some debuggers to remove, a router file that isn't being used, and a couple small things to refactor

2022-05-03 20:24 UTC, dovakeen118 commented on client/src/components/AttractionShowPage.js
> +  //debugger
DEBUGGER

2022-05-03 20:24 UTC, dovakeen118 commented on client/src/components/AttractionsList.js
> +  //debugger
DEBUGGER

2022-05-03 20:24 UTC, dovakeen118 commented on server/src/db/migrations/20220503184204_createReviews.cjs
> +        table.string("content")
might consider making this a type of `text` for a larger character limit on the content of the review

2022-05-03 20:24 UTC, dovakeen118 commented on server/src/db/migrations/20220503184204_createReviews.cjs
> +    return knex.schema.createTable("reviews", (table) => {
This file appears to have a tab size of 4 spaces, while other files in the app have a tab size of 2. This should be consistent for all group members, you can change this setting in VSCode to set the `tab size` of your editor to 2!

2022-05-03 20:24 UTC, dovakeen118 commented on server/src/routes/api/v1/attractionsReviewsRouter.js
> +    try {
we can remove the empty space on line 8

actually, this router isn't used at all and should be removed!

2022-05-03 20:24 UTC, dovakeen118 commented on client/src/components/AttractionShowPage.js
> +    attractions: [],
I don't think we want an array of `attractions` here on the show page, but instead the one attraction object with it's reviews

2022-05-03 21:02 UTC, camziny reviewed
removed debugger from AttractionsList,
changed content from "string" to "text" in reviews migration,
adjusted formatting in reviews migration,
removed attractionsReviewsRouter,
adjusted useState in AttractionShowPage.

2022-05-04 20:51 UTC, nwalberts approved these changes

2022-05-04 20:51 UTC, nwalberts commented on client/src/components/postReview.js
> +    }
this isnt a components, so put it in its own "requests" or "api" folder

2022-05-04 20:51 UTC, nwalberts commented on server/src/db/seeders/AttractionSeeder.js
> +      },
I love the goofiness, but I would seed data that is slightly less jokey since employers will get confused

2022-05-04 20:51 UTC, nwalberts commented on server/src/routes/api/v1/attractionsRouter.js
> +    return res.status(200).json({ attraction })
this should use a serializer, but ill let it pass for now

2022-05-04 22:11 UTC, br-ndt approved these changes
approving these changes, out of the norm established for group projects, with permission from @nwalberts

2022-05-04 22:11 UTC, merged