Rendering update
br-ndt/trip pull request #8
Opened 2022-05-06 18:08 UTC by JeanCGedeon

fix fetch request on the front-end
add userId into state on the front-end
edit the top bar
add attractionReviewsRouter(also update userId in the post request)

2022-05-06 20:17 UTC, nwalberts requested changes

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/App.js
> +      </Route>
This would be considered an incomplete feature. Ill leave for now because your app came with something similar, but we really should just delete this until we have something for this page

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +  const attractionDescription = attraction.description || "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
both of these are considered "filler text" and mark an incomplete feature. These elements either shouldnt appear on the page at all, or be based on data from your backend. No filler

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +      </div>
The div and h4 here are part of what makes up the form. Though the div currently so serves no purpose
- delete the div entirely 
- move the h4 into the NewReviewForm

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +  }
yooo this is an incomplete feature. If we add this review, it wont get persisted in the database. This should post to the backend and persist the features. No half measures please!

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/AttractionsList.js
> +      </div>
this div is serving no purpose, please delete

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>    });
placeholders are not allowed, this marks another incomplete feature. Either have this independent of a location or find another way

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>    });
Furthermore, you shouldnt be storing a locationId in state in the first place. It should be something passed down via props

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
> +        props.addNewAttraction(body.attraction);
no code comments, remove line 32

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
> +
....we dont need these extra lines. Please delete

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/AttractionsList.js
> +      </div>
Im pretty confused, because in your form, you redirect to the AttractionList page....but you are already on the attraction list page

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
yo, you all need to decide, if this form lives on the index page and if the form submission adds the new attraction to state (and posts) or if this form lives on its own page and redirects back to attractions. Im rather confused

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
> -      <h3>Add a New Attraction</h3>
I actually liked that h3 here...

Also the div on line 57 is serving no purpose, please delete

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>          <input type="text" name="name" placeholder="The Colosseum" onChange={handleInputChange}/>
all of the placeholders in this form should be deleted, they don't inform the user on how to fill out the form, and would confuse users and emplpyers

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewReviewForm.js
>    });
No placeholder values, and userId should not be tracked in state here. It should be passed down via props from App.js

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewReviewForm.js
> +      userId: 1
delete

2022-05-06 20:17 UTC, nwalberts commented on package.json
> +    "yarn": "^1.22.17"
is there a reason for the yarn change? Did you discuss this as a group?

2022-05-06 20:17 UTC, nwalberts commented on server/src/routes/api/v1/attractionReviewsRouter.js
> +});
user id should come from your passport session, via `req.user`, not from the frontend.

2022-05-06 20:17 UTC, nwalberts commented on server/src/routes/api/v1/attractionReviewsRouter.js
> +});
there is also no ValidationError handling here. You are handling for these types of errors on the frontend, but in this implementation those errors would never be used

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewReviewForm.js
> +          return setErrors(newErrors);
wait...where is `setErrors` defined? Are those errors ever used and displayed anywhere?

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>          }
you are going to need to update this post fetch request. Now that you have a location, the path should be nested 
```
fetch("/api/v1/locations/:locationId/attractions", ...)
```

2022-05-06 20:17 UTC, nwalberts commented on server/src/routes/api/v1/attractionsRouter.js
> +  const { name, description, locationId } = cleanUserInput(req.body);
the locationId shouldnt be in the body. Per my comment in your form, you should have locationId in your params, not the body. 

You are going to need to move this post into an locationAttractions router

2022-05-06 20:17 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>    });
This newAttractionForm either needs to be on the LocationShowPage, or on its own page. Otherwise, we have no idea which location this is being added to. 

alterantively, you can have an attractions have an _optional_ BelongsToOne relationship with location, but that would require some updates

2022-05-06 20:17 UTC, nwalberts commented on server/src/routes/api/v1/attractionsRouter.js
> +    console.log(error);
remove this

2022-05-09 15:04 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +  }
I misspoke. The names you have here are confusing. You have one addNewReview method in the form, and one here. Let's disambiguate these two and rename either this one or the one with the POST

2022-05-09 15:04 UTC, nwalberts commented on client/src/components/AttractionsList.js
> +  }
this is used in another `AddNewAttraction` method which is very confusing, lets rename one of them (probably the method that has the POST

2022-05-09 15:04 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>          }
alternatively, you can
- add a dropdown with locations 
- add this entire form to the LocationShow
- make this its in own page

2022-05-09 15:04 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>    });
As we talked, we also said you could have a dropdown of locations to set for this new attraction. In which case, the locationId CAN be tracked in state

2022-05-09 15:04 UTC, nwalberts commented on client/src/components/NewAttractionForm.js
>          <input type="text" name="name" placeholder="The Colosseum" onChange={handleInputChange}/>
maybe something a little more relatable ::P

2022-05-09 17:46 UTC, br-ndt commented on client/src/components/App.js
> +      </Route>
Changed the rendered component to be a Redirect to "/attractions"

2022-05-09 17:54 UTC, br-ndt commented on client/src/components/AttractionShowPage.js
> +  const attractionDescription = attraction.description || "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
Changed these filler/hardcode values to be conditionally-rendered elements.

2022-05-09 17:57 UTC, br-ndt commented on client/src/components/AttractionShowPage.js
> +  }
Function names changed to postAttraction/postReview

2022-05-09 19:27 UTC, br-ndt commented on client/src/components/NewAttractionForm.js
>          }
Added location dropdown list to NewAttractionForm
Added error handling for this new POST route, located in locationAttractionsRoute

2022-05-09 21:01 UTC, merged