Review delete
br-ndt/trip pull request #9
Opened 2022-05-10 18:03 UTC by acameron724

2022-05-10 18:04 UTC, acameron724 commented
finish deleteReview function
edit reviewRouter res.status

Co-authored-by: camziny <camziny@users.noreply.github.com>
Co-authored-by: Fabricius Eusebio <yoFabricius@users.noreply.github.com>
Co-authored-by: Tyler <br.ndt.tyler@gmail.com>

2022-05-10 18:51 UTC, dovakeen118 reviewed
Nice work! there's a couple things to implement to fully complete the feature, and a few recommendations

2022-05-10 18:51 UTC, dovakeen118 commented on server/src/routes/api/v1/reviewsRouter.js
> +    await Review.query().deleteById(req.params.id)
We wouldn't want someone to be able to delete someone else's review, and can check for that in the router here to see if the current user (`req.user`) is the same user that created this review to be deleted

2022-05-10 18:51 UTC, dovakeen118 commented on client/src/components/ReviewTile.js
> +        <input type="submit" value="Delete Review"/>
we could instead make this a button and move the `onClick` to that element as well - I'd say though the key piece is putting the synthetic click event as close to the actual thing that's being interacted with

2022-05-10 18:51 UTC, dovakeen118 commented on client/src/components/ReviewTile.js
> +        <input type="submit" value="Delete Review"/>
you might also consider only making this delete visible if the signed in user is the same one who created the review

2022-05-11 17:15 UTC, nwalberts requested changes

2022-05-11 17:15 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +
unfortunately I have to b e a stickler. the indentation is off!

2022-05-11 17:15 UTC, nwalberts commented on client/src/components/AttractionShowPage.js
> +      } else {
you control for 422, but your router isnt setup to respond with a 422 here. Instead, please prepare for a 401 error

2022-05-11 18:23 UTC, merged